### PR TITLE
update patches loading to support v6.1.0 and cpu-max

### LINKED ISSUE #59: Building for qemu v6.1.0
### Discussed in https://github.com/tonistiigi/binfmt/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **jonathan-albrecht-ibm** August 25, 2021</sup>
I tried building binfmt against the newly released qemu v6.1.0 but hit a compile error. @crazy-max it's the same error as seen in the recent release GitHub action https://github.com/tonistiigi/binfmt/actions/runs/1164593346

I just wanted to note that I tried building without applying the alpine aport qemu patches (https://github.com/tonistiigi/binfmt/blob/99c76af6d6aec693ab9195190055c0262d95d667/Dockerfile#L20) and everything was successful. It looks like there were some fixes in qemu since v6.0.0 to help compiling against musl. I think its the https://github.com/alpinelinux/aports/blob/master/community/qemu/fix-sigevent-and-sigval_t.patch that now causes the compilation error but I haven't looked to closely.

I don't know if any of the other patches are needed for other reasons though.

Hope that helps.</div>

### PR DESCRIPTION
**Pull request by tonistiigi**
closes #59

Modifies patches loading to
- support loading custom patches via build-arg, eg for cpu-max and buildkit embedded target patches 
- support custom selection of alpine patches for qemu v6.1.0

The alpine/musl patches situation isn't very stable. Current works with v6.0 and v6.1 . Doesn't work with 5.x and may break when alpine/musl updates. I think we might need a "config file" with specific sports commit for specific version ranges or version-based patch loading from local files. If we copy patches from aports to this repo we also need to add exceptions for them to license as I don't know where they are coming from and they could be gpl. We can work on this as follow-up.

@crazy-max 

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
Alpine updated their patches to v6.1 and I made our selection to match theirs with version based ranges(+additional out patches). If needed the `aports.config` can be extended in the future with more fields with additional exceptions (eg. if we include our patches only for a specific range).

**Review by crazy-max — APPROVED** [review]
LGTM
